name: Build

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main", "develop"]
  schedule:
    - cron: "30 5 * * 1"

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build . -f Dockerfile -t thequoter:$(date +%s)
