name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm test

      - name: Build app
        run: npm run build

      - name: Build Docker image
        run: docker build . -f Dockerfile -t thequoter:$(git log -1 --format=%h)
