name: Build and push to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  prod-build:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: maximmaxims/thequoter:latest
